dl
format = edgelist1	
n=28	
data:
pass new 1.0	
plenty much 1.0	
yard pass 1.0	
use nt 1.0	
rum nt 1.0	
rum give 1.0	
stop plenty 1.0	
nt much 1.0	
want nt 1.0	
want give 1.0	
tashtego maintopsail 1.0	
tashtego new 1.0	
use plenty 1.0	
rum glass 1.0	
want rum 1.0	
yard maintopsail 1.0	
new lash 1.0	
use much 1.0	
pass lash 1.0	
lash around 1.0	
tashtego pass 1.0	
stop much 1.0	
want use 1.0	
new around 1.0	
stop lash 1.0	
plenty around 1.0	
stop around 1.0	
yard tashtego 1.0	